# Build an executable named assign2 from test_assign2_1.c

all : test_assign2_1.c dberror.c buffer_mgr.h buffer_mgr_stat.h dberror.h dt.h storage_mgr.h test_helper.h 
	gcc -o assign2.exe dberror.c test_assign2_1.c

rm : assign2.exe
	rm assign2.exe
